version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix" # Prefiks commitów dla aktualizacji
    versioning-strategy: "auto"